
services:
  # 1. The Database Service
  db:
    image: mysql:8.0
    container_name: mysql_local_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_portal_db
    ports:
      - "3306:3306" # Maps container port 3306 to your actual PC port 3306
    volumes:
      - mysql_data:/var/lib/mysql # Keeps your database data safe even if container stops
      - ./db-init:/docker-entrypoint-initdb.d
    command: --lower_case_table_names=1
  # 2. The Node.js Backend Service
  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db # Docker automatically resolves the service name "db" as the IP
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=student_portal_db
      - PORT=3000
    depends_on:
      - db # Makes sure the database starts before the backend does

volumes:
  mysql_data: